### ISSUE TITLE
Language - Add english text

### ISSUE THREAD

**Issue by Ziedelth** [Z-Jais/Application#255]
Dictionnary, based on phone language?

**Comment by SputNikPlop** [comment]
We could do https://docs.flutter.dev/ui/accessibility-and-localization/internationalization that way we could have both French and English plus any other languages

**Comment by Ziedelth** [comment]
> We could do https://docs.flutter.dev/ui/accessibility-and-localization/internationalization that way we could have both French and English plus any other languages

Thank, I will check this
I just need to know, if we can set a default language, because if I haven't Spain language, how the app will be rendered

**Comment by SputNikPlop** [comment]
> Thank, I will check this I just need to know, if we can set a default language, because if I haven't Spain language, how the app will be rendered
I believe this is possible, I made a suggestion that should account for this.

**Comment by Ziedelth** [comment]
Late scheduled, not ready with the new modifications
